.TH STIR_SHAKEN_AS_DIV 1
.SH NAME
stir_shaken_as_div \- STIR/SHAKEN diversion authentication example
.SH SYNOPSIS
.B stir_shaken_as_div
.SH DESCRIPTION
.B stir_shaken_as_div
demonstrates creating a DIV PASSporT SIP Identity header for a diverted call
using libstirshaken.
.SH SEE ALSO
.BR stirshaken (1)
