.TH STIR_SHAKEN_AS_BASIC 1
.SH NAME
stir_shaken_as_basic \- basic STIR/SHAKEN authentication service example
.SH SYNOPSIS
.B stir_shaken_as_basic
.SH DESCRIPTION
.B stir_shaken_as_basic
demonstrates creating and signing a SHAKEN PASSporT and wrapping it in a SIP
Identity header using libstirshaken.
.SH SEE ALSO
.BR stirshaken (1)
