.TH STIR_SHAKEN_CERT_REQ 1
.SH NAME
stir_shaken_cert_req \- sample STIR/SHAKEN certificate request client
.SH SYNOPSIS
.B stir_shaken_cert_req
.SH DESCRIPTION
.B stir_shaken_cert_req
demonstrates requesting a STIR/SHAKEN service provider certificate using
libstirshaken.
.SH SEE ALSO
.BR stirshaken (1)
