.TH STIR_SHAKEN_VS_BASIC 1
.SH NAME
stir_shaken_vs_basic \- basic STIR/SHAKEN verification service example
.SH SYNOPSIS
.B stir_shaken_vs_basic
.SH DESCRIPTION
.B stir_shaken_vs_basic
demonstrates verifying a SHAKEN PASSporT and SIP Identity header using
libstirshaken.
.SH SEE ALSO
.BR stirshaken (1)
