---
kind: pipeline
name: scan-build

node:
  freeswitch: stack

steps:
    - name: scan-build
      image: signalwire/freeswitch-public-base
      pull: true
      commands:
      - apt-get update && apt-get install -y clang-tools-7 libcurl4-openssl-dev libjwt-dev libks
      - ./bootstrap.sh
      - ./configure --enable-address-sanitizer
      - mkdir -p scan-build
      - echo '#!/bin/bash\nscan-build-7 -o ./scan-build/ make -j`nproc --all` |& tee ./scan-build-result.txt\nexitstatus=$${PIPESTATUS[0]}\necho $$exitstatus > ./scan-build-status.txt\n' > scan.sh
      - chmod +x scan.sh
      - ./scan.sh
      - exitstatus=`cat ./scan-build-status.txt`
      - echo "*** Exit status is $exitstatus"
      - make install
      - make check

    - name: notify
      image: signalwire/scan-build-notify
      pull: true
      environment:
        GITHUB_CI_APP_PEM:
          from_secret: github_ci_app_pem
        SSH_KEY:
          from_secret: ssh_key
        SLACK_WEBHOOK_URL:
          from_secret: slack_webhook_url
      commands:
      - /root/notify.sh

      
trigger:
  branch:
  - master
  event:
  - pull_request
  - push
---
kind: signature
hmac: 700f49ce871925296c00888ff8842aba8f5d1660ccea1784b07a20ab8619ec22

...
